version: '3.8'

services:
  prometheus-service-demo-0:
    image: docker.io/julius/prometheus-demo-service:latest
    container_name: prometheus-service-demo-0
    ports:
      - "10000:8080"

  prometheus-service-demo-1:
    image: docker.io/julius/prometheus-demo-service:latest
    container_name: prometheus-service-demo-1
    ports:
      - "20000:8080"

  prometheus-service-demo-2:
    image: docker.io/julius/prometheus-demo-service:latest
    container_name: prometheus-service-demo-2
    ports:
      - "30000:8080"

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

volumes:
  grafana-storage:
