{
 "title": "PromQL",
 "description": "90th Percentile HTTP Request Duration (Grouped by Path, Method, and Status)\n95th Percentile API HTTP Request Duration (Grouped by Path and Method)\nAverage HTTP Request Duration (Grouped by Path and Method)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average HTTP Request Duration (5m)",
   "type": "timeseries",
   "description": "This panel shows the average HTTP request duration for all API paths and methods over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m]))\nwithout (path, method)\n/\nsum(rate(demo_api_request_duration_seconds_count[5m]))\nwithout (path, method)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Percentiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "90th Percentile API Request Duration",
   "type": "stat",
   "description": "Displays the 90th percentile of API request durations over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.90,\n    sum(rate(demo_api_request_duration_seconds_bucket[5m]))\n    without (path, method, status)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile API Request Duration",
   "type": "bargauge",
   "description": "Shows the duration for 95% of requests over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(rate(demo_api_request_duration_seconds_bucket[5m]))\n    without (path, method)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}